foreground            #FBECD8
background            #110000
cursor                #B38E7C
selection_background  #F1DCBF
selection_foreground  #110000

color0  #110000
color8  #A89A86
color1  #6C2F1F
color9  #6C2F1F
color2  #6C2F1F
color10 #6C2F1F
color3  #7D422D
color11 #7D422D
color4  #EBC08A
color5  #F3C991
color6  #F3C991
color14 #F3C991
color7  #F1DCBF
color15 #F1DCBF
