$background = rgb(110000)
$foreground = rgb(FBECD8)
$color0 = rgb(110000)
$color1 = rgb(6C2F1F)
$color2 = rgb(6C2F1F)
$color3 = rgb(7D422D)
$color4 = rgb(EBC08A)
$color5 = rgb(F3C991)
$color6 = rgb(F3C991)
$color7 = rgb(F1DCBF)
