$background = rgb(372C2B)
$foreground = rgb(DBCDD5)
$color0 = rgb(5D5150)
$color1 = rgb(5E2C30)
$color2 = rgb(6A3941)
$color3 = rgb(754753)
$color4 = rgb(815565)
$color5 = rgb(8D6276)
$color6 = rgb(997088)
$color7 = rgb(C4AFBB)
